AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role that can be assumed by any principal in account 851725397705

Resources:
  CodeStarConnectionCCCNoConditions:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeStarConnectionCCCNoConditions
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::851725397705:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
  CodeStarConnectionCCCFullRepositoryIdConditionAll:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeStarConnectionCCCFullRepositoryIdConditionAll
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::851725397705:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Condition:
                  StringEquals:
                    "codeconnections:FullRepositoryId": 
                      - "thomaspreece-test-org/repo-1"
                      - "thomaspreece-test-org/repo-2"
  CodeStarConnectionCCCFullRepositoryIdConditionOne:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeStarConnectionCCCFullRepositoryIdConditionOne
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::851725397705:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Condition:
                  StringEquals:
                    "codeconnections:FullRepositoryId": 
                      - "thomaspreece-test-org/repo-1"
  CodeStarConnectionCCCPermissionsConditionAll:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeStarConnectionCCCPermissionsConditionAll
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::851725397705:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Condition:
                  StringEquals:
                    "codeconnections:ProviderPermissionsRequired": "read_write"
  CodeStarConnectionCCCPermissionsConditionOne:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeStarConnectionCCCPermissionsConditionOne
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::851725397705:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Condition:
                  StringEquals:
                    "codeconnections:ProviderPermissionsRequired": "read_only"
  CodeStarConnectionCCCActionConditionAll:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeStarConnectionCCCActionConditionAll
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::851725397705:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Condition:
                  StringEquals:
                    "codeconnections:ProviderAction": 
                      - "GetBranch"
                      - "ListRepositories"
                      - "ListOwners"
                      - "ListBranches"
                      - "StartUploadArchiveToS3"
                      - "GitPush"
                      - "GitPull"
                      - "GetUploadArchiveToS3Status"
                      - "CreatePullRequestDiffComment"
                      - "GetPullRequest"
                      - "ListBranchCommits"
                      - "ListCommitFiles"
                      - "ListPullRequestComments"
                      - "ListPullRequestCommits"                    
  CodeStarConnectionCCCActionConditionOne:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeStarConnectionCCCActionConditionOne
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::851725397705:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Condition:
                  StringEquals:
                    "codeconnections:ProviderAction": 
                      - "GetBranch"                                    